// Bakes zyn's factory presets into a C++ header. Embedding rather than loading
// a file at runtime keeps the plugin self-contained: no resource path to
// resolve, nothing to go missing on someone else's machine.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ZYN = process.env.ZYN_DIR ?? "C:/dev/zyn";
const OUT = resolve(here, "../core/include/sl/FactoryPresets.h");

const presets = JSON.parse(readFileSync(resolve(ZYN, "default-presets.json"), "utf8"));
const zynCommit = execSync(`git -C "${ZYN}" rev-parse HEAD`).toString().trim();

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

const rows = presets.map((p) => {
  const type = p.type !== undefined ? p.type : Math.abs(p.seed) % 10;
  const octave = p.octave !== undefined ? p.octave : 0;
  const volume = p.volume !== undefined ? p.volume : 1.0;
  return `    {"${esc(p.name)}", ${p.seed}u, ${type}, ${octave}, ${volume}},`;
}).join("\n");

const header = `#pragma once
#include <cstdint>

// GENERATED by tools/export-presets.mjs from zyn ${zynCommit.slice(0, 8)}.
// Do not edit by hand; re-run the script instead.

namespace sl {

struct FactoryPreset {
    const char* name;
    uint32_t seed;
    int typeIndex;   // 0-9, the seed's last digit
    int octave;
    double volume;
};

inline constexpr FactoryPreset kFactoryPresets[] = {
${rows}
};

inline constexpr int kNumFactoryPresets =
    static_cast<int>(sizeof(kFactoryPresets) / sizeof(kFactoryPresets[0]));

} // namespace sl
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, header);
console.log(`wrote ${presets.length} factory presets from zyn ${zynCommit.slice(0, 8)}`);
